name: "KiBot - Fabrication and Documentation (tag + release)"
on:
  push:
    tags:
      - pcb-v*


jobs:
  FabricationOutputs:
    env:
      BaseFileName: temp4c
      Timezone: America/New_york
      OutputFolder: PCB/KiBotOutput
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: KiBot
        uses: INTI-CMNB/KiBot@v1_k6
        with:
          config: PCB/.kibot/temp4c.kibot.yaml
          dir: ${{ env.OutputFolder }}
          schema: PCB/temp4c.kicad_sch
          board: PCB/temp4c.kicad_pcb

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BaseFileName }}-${{ env.github_ref_name }}
          path: ${{ env.OutputFolder }}/**
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.OutputFolder }}/*.zip
            ${{ env.OutputFolder }}/*.pdf
        